language: node_js
node_js: 
  - "6.11"
install:
  - yarn
script:
  - yarn lint
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master